[package]
name = "kitt-native-python"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "kitt_native"
crate-type = ["cdylib"]

[dependencies]
kitt-native-engine = { path = "../kitt-native-engine" }
pyo3 = { workspace = true }
pythonize = { workspace = true }
serde = { workspace = true }

[package.metadata.maturin]
name = "kitt_native"
